<?php
if (!session()->get('isLoggedIn')) {
    return redirect()->to(site_url('admin'));
}

if (!isset($member)) {
    return redirect()->to(site_url('admin/members-report'));
}
?>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> 
      <a href="<?= site_url('admin') ?>" title="Go to Home" class="tip-bottom"><i class="fas fa-home"></i> Home</a> 
      <a href="<?= site_url('admin/members-report') ?>" class="current">Member Reports</a> 
    </div>
    <h1 class="text-center">Member's Report <i class="fas fa-file"></i></h1>
  </div>
  <div class="container-fluid print-container">
    <div class="row-fluid">
      <div class="span12">
	      <div class="widget-box"> 
      
     <div class="widget-content">
            <div class="row-fluid">
              <div class="span4">
                <table class="">
                  <tbody>
                    <tr>
                      <td><h4>Perfect GYM Club</h4></td>
                    </tr>
                    <tr>
                      <td>5021  Wetzel Lane, Williamsburg</td>
                    </tr>
                    
                    <tr>
                      <td>Tel: 231-267-6011</td>
                    </tr>
                    <tr>
                      <td >Email: support@perfectgym.com</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              
              <div class="span8">
                <table class="table table-bordered table-invoice-full">
                  <thead>
                    <tr>
                      <th class="head0">Membership ID</th>
                      <th class="head1">Services Taken</th>
                      <th class="head0 right">My Plans (Upto)</th>
                      <th class="head1 right">Address</th>
                      <th class="head0 right">Charge</th>
                      <th class="head0 right">Attendance Count</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><div class="text-center">PGC-SS-<?php echo $member['user_id']; ?></div></td>
                      <td><div class="text-center"><?php echo htmlspecialchars($member['services']); ?></div></td>
                      <td><div class="text-center"><?php if($member['plan'] == 0) { echo 'NONE';} else {echo $member['plan'].' Month/s';} ?></div></td>
                      <td><div class="text-center"><?php echo htmlspecialchars($member['address']); ?></div></td>
                      <td><div class="text-center">₹<?php echo number_format($member['amount'], 2); ?></div></td>
                      <td><div class="text-center"><?php echo $member['attendance_count']; ?> Day/s</div></td>
                    </tr>
                  </tbody>
                </table>
                <table class="table table-bordered table-invoice-full">
                  <tbody>
                    <tr>
                      <td class="msg-invoice" width="55%"> <div class="text-center"><h4>Last Payment Done: ₹<?php echo number_format($member['amount'], 2); ?>/-</h4>
                        <em><a href="#" class="tip-bottom" title="Registration Date" style="font-size:15px;">Member Since: <?php echo $member['dor']; ?> </a></em> </td>
                        </div>
                    </tr>
                  </tbody>
                </table>
              </div> <!-- end of span 12 -->
              
            </div>

            <div class="row-fluid">
                <div class="pull-left">
                <h4>Member <?php echo htmlspecialchars($member['fullname']); ?>,<br/> <br/> Membership is currently <strong><?php echo htmlspecialchars($member['status']); ?></strong>! <br/></h4><p>Thank you for choosing our services.<br/>- on the behalf of whole team</p>
                </div>
                <div class="pull-right">
                  <h4><span>Approved By:</h4>
                  <img src="<?= base_url('img/report/stamp-sample.png') ?>" width="124px;" alt=""><p class="text-center">Note:AutoGenerated</p> </div>
                  
            </div>
          </div>
   
		</div>
	
      </div>
    </div>

  </div>

  <div class="text-center">
    <button class="btn btn-danger" onclick="window.print()"><i class="fas fa-print"></i> Print</button>
  </div>

</div>

